apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: open5gs-smf
        pfcp:
          dev: {{ .Values.smf.pfcp.interface }}
        gtpc:
          dev: {{ .Values.smf.gtpc.interface }}
        gtpu:
          dev: {{ .Values.smf.gtpu.interface }}    
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
         - addr: 10.45.1.1/16
           dnn: {{ .Values.dnn2 }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: open5gs-nrf 

    upf:
      pfcp:
      - name: upf-open5gs
        addr: {{ .Values.upfmain.addr }}
        dnn: {{ .Values.dnn }}
      - addr: {{ .Values.upfmec.addr }}
        dnn: {{ .Values.dnn2 }}

